# Generated by Django 6.0.6 on 2026-06-30 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Chuyển tab/cửa sổ'), ('window_blur', 'Mất focus cửa sổ'), ('fullscreen_exit', 'Thoát toàn màn hình'), ('copy_paste', 'Copy/Paste'), ('right_click', 'Click chuột phải'), ('devtools', 'Mở DevTools'), ('multiple_faces', 'Phát hiện nhiều người'), ('no_face', 'Không phát hiện khuôn mặt'), ('suspicious', 'Hành vi đáng ngờ'), ('submitted', 'Nộp bài')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao')], default='low', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='results.examsession')),
            ],
            options={
                'verbose_name': 'Sự kiện giám sát',
                'verbose_name_plural': 'Sự kiện giám sát',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('tab_switches', models.PositiveIntegerField(default=0)),
                ('window_blurs', models.PositiveIntegerField(default=0)),
                ('suspicious_count', models.PositiveIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao')], default='low', max_length=10)),
                ('flagged', models.BooleanField(default=False, verbose_name='Đánh dấu gian lận')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú giám thị')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_report', to='results.examsession')),
            ],
            options={
                'verbose_name': 'Báo cáo giám sát',
                'verbose_name_plural': 'Báo cáo giám sát',
            },
        ),
    ]
