# Generated by Django 6.0.6 on 2026-06-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringreport',
            name='total_violations',
            field=models.PositiveIntegerField(default=0, verbose_name='Tổng số lần vi phạm'),
        ),
    ]
