# Generated by Django 6.0.6 on 2026-06-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phòng ban/Team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('teacher', 'Quản lý đào tạo'), ('student', 'Nhân viên')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã nhân viên'),
        ),
    ]
