# Generated by Django 6.0.6 on 2026-06-30 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tiêu đề bài kiểm tra')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('exam_type', models.CharField(choices=[('single', 'Trắc nghiệm 1 đáp án'), ('multiple', 'Trắc nghiệm nhiều đáp án'), ('true_false', 'Đúng / Sai'), ('mixed', 'Tổng hợp')], default='mixed', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('scheduled', 'Đã lên lịch'), ('active', 'Đang diễn ra'), ('ended', 'Đã kết thúc')], default='draft', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Thời gian làm bài (phút)')),
                ('total_points', models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='Tổng điểm')),
                ('pass_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='Điểm đạt')),
                ('max_attempts', models.PositiveSmallIntegerField(default=1, verbose_name='Số lần thi tối đa')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Đảo thứ tự câu hỏi')),
                ('shuffle_choices', models.BooleanField(default=True, verbose_name='Đảo thứ tự đáp án')),
                ('show_result_immediately', models.BooleanField(default=True, verbose_name='Hiển thị kết quả ngay')),
                ('show_correct_answers', models.BooleanField(default=False, verbose_name='Hiển thị đáp án đúng')),
                ('prevent_cheating', models.BooleanField(default=True, verbose_name='Bật chống gian lận')),
                ('allow_review', models.BooleanField(default=True, verbose_name='Cho phép xem lại')),
                ('is_public', models.BooleanField(default=False, verbose_name='Bài thi công khai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='questions.subject')),
            ],
            options={
                'verbose_name': 'Bài kiểm tra',
                'verbose_name_plural': 'Bài kiểm tra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=100, verbose_name='Giao cho lớp')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_given', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.exam')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phân công bài thi',
                'verbose_name_plural': 'Phân công bài thi',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'verbose_name': 'Câu hỏi trong bài thi',
                'verbose_name_plural': 'Câu hỏi trong bài thi',
                'ordering': ['order'],
                'unique_together': {('exam', 'question')},
            },
        ),
    ]
