# Generated by Django 6.0.6 on 2026-06-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examassignment',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Giao cho phòng ban/team'),
        ),
    ]
