# Generated by Django 6.0.6 on 2026-07-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examassignment_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('scheduled', 'Đã lên lịch'), ('active', 'Đang diễn ra'), ('paused', 'Tạm dừng'), ('ended', 'Đã kết thúc')], default='draft', max_length=20),
        ),
    ]
